In [13]:
import pandas as pd

df = pd.read_csv('data/df_clean.csv')

df.assign(
    sous_poids = (df['bmi']<18.5).astype(int), #.astype permet de convertir des bool en entiers (T =1 , F= 0)
    poids_normal = ((df['bmi']>= 18.5) & (df['bmi']<24.9)).astype(int),
    surpoids = ((df['bmi']>=24.9) & (df['bmi']<29.9)).astype(int),
    obésité_modérée =((df['bmi']>= 29.9) & (df['bmi']<34.9)).astype(int),
    obésité_morbide = ((df['bmi']>=34.9)).astype(int)
)

,age,sex,bmi,children,smoker,region,charges,sous_poids,poids_normal,surpoids,obésité_modérée,obésité_morbide
0,19,female,27.900,0,yes,southwest,16884.92400,0,0,1,0,0
1,18,male,33.770,1,no,southeast,1725.55230,0,0,0,1,0
2,28,male,33.000,3,no,southeast,4449.46200,0,0,0,1,0
3,33,male,22.705,0,no,northwest,21984.47061,0,1,0,0,0
4,32,male,28.880,0,no,northwest,3866.85520,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1332,50,male,30.970,3,no,northwest,10600.54830,0,0,0,1,0
1333,18,female,31.920,0,no,northeast,2205.98080,0,0,0,1,0
1334,18,female,36.850,0,no,southeast,1629.83350,0,0,0,0,1
1335,21,female,25.800,0,no,southwest,2007.94500,0,0,1,0,0
1336,61,female,29.070,0,yes,northwest,29141.36030,0,0,1,0,0

In [16]:
import pandas as pd


def categorisation_numerique(df, bins, labels, categorie):
    df = df.drop(['charges'], axis=1)
    df['nouvelle_categorie'] = pd.cut(df[categorie], bins=bins, labels=labels, right=False)
    categorie_dummies = pd.get_dummies(df['nouvelle_categorie'], prefix=categorie, drop_first=True)
    df = pd.concat([df, categorie_dummies], axis=1)
    df = df.drop(['nouvelle_categorie'], axis=1)
    return df

df = pd.read_csv('data/df_clean.csv')

df = categorisation_numerique(df, [0, 18.5, 24.9, 28.5, 35, 40, float('inf')],
                               ['maigreur', 'sous_poids', 'poids_normal', 'surpoids', 'obésité', 'obésité_morbide'],
                               'bmi')

NameError: name 'categorie_dummies' is not defined