In [10]:
import pandas as pd
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
from sklearn.linear_model import LinearRegression

In [14]:
def categorisation_numerique(df, bins, labels, categorie):
    df = df.drop(['charges'], axis=1)
    df['nouvelle_categorie'] = pd.cut(df[categorie], bins=bins, labels=labels, right=False)
    categorie_dummies = pd.get_dummies(df['nouvelle_categorie'], prefix=categorie, drop_first=True)
    df = pd.concat([df, categorie_dummies], axis=1)
    df = df.drop(['nouvelle_categorie'], axis=1)
    return df

df = pd.read_csv('data/df_clean.csv')

df = categorisation_numerique(df, [0, 18.5, 24.9, 28.5, 35, 40, float('inf')],
                               ['maigreur', 'sous_poids', 'poids_normal', 'surpoids', 'obésité', 'obésité_morbide'],
                               'bmi')
df

,age,sex,bmi,children,smoker,region,bmi_sous_poids,bmi_poids_normal,bmi_surpoids,bmi_obésité,bmi_obésité_morbide
0,19,female,27.900,0,yes,southwest,False,True,False,False,False
1,18,male,33.770,1,no,southeast,False,False,True,False,False
2,28,male,33.000,3,no,southeast,False,False,True,False,False
3,33,male,22.705,0,no,northwest,True,False,False,False,False
4,32,male,28.880,0,no,northwest,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...
1332,50,male,30.970,3,no,northwest,False,False,True,False,False
1333,18,female,31.920,0,no,northeast,False,False,True,False,False
1334,18,female,36.850,0,no,southeast,False,False,False,True,False
1335,21,female,25.800,0,no,southwest,False,True,False,False,False
1336,61,female,29.070,0,yes,northwest,False,False,True,False,False